### ISSUE TITLE
Issue retrieving non-english student text

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-API#171]
Report from Cristian R: Tables content does not support UTF-8 (extended ASCII characters like accents). Originally this issue was created in WISE-Client.

The main issue is that the getStudentData endpoint is not sending back the text in the right format. The API appears to be saving non-english student text correctly.

**Comment by cienciascontic** [comment]
None of the components support UTF-8 (except Rich Text Format items), not just the table. Nor the open response. See the image below:
![image](https://user-images.githubusercontent.com/6078186/184171240-2f761521-558c-4dd3-b07f-a48242dad2ed.png)
