### ISSUE TITLE
Bug: Teacher can't open grading tool

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-API#68]
### Description

When a teacher (not a shared teacher or admin) goes to open a grading tool for a run that they own, they see a blank screen.

The culprit is this method returns false due to [changes made in this PR](https://github.com/WISE-Community/WISE-API/pull/65)
```
  private Boolean isTeacherAssociatedWithRun(Run run, User user) {
    return (user.isTeacher() && run.isTeacherAssociatedToThisRun(user)) || user.isAdmin();
  }
```

The user object is now HibernateProxy object and run.isTeacherAssociatedToThisRun(user) returns false.

**Comment by geoffreykwan** [comment]
Fixed in https://github.com/WISE-Community/WISE-API/pull/69
