### ISSUE TITLE
fix(PeerGroupActivity): prevent duplicate tags

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-API#97]
Prevent duplicate peerGroupActivityTags from being saved for a run.

**Comment by geoffreykwan** [comment]
Fixed in [13dd34502990363511fa9dd32ea1610de24a47f4](https://github.com/WISE-Community/WISE-Client/commit/13dd34502990363511fa9dd32ea1610de24a47f4) and 1c27adb31e09ade9b86ac66b64ab43523627c276
